// Code generated by swaggo/swag. DO NOT EDIT.

package public

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Выполняет авторизацию пользователя",
                "tags": [
                    "login"
                ],
                "summary": "Log in",
                "operationId": "login",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Required parameters not filled",
                        "schema": {}
                    },
                    "403": {
                        "description": "Insufficient rights to perform the operation",
                        "schema": {}
                    }
                }
            }
        },
        "/verify": {
            "post": {
                "description": "Выполняет проверку токенов пользователя, которые получает из cookies после выполнения /login запроса",
                "tags": [
                    "verify"
                ],
                "summary": "Verify",
                "operationId": "verify",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Insufficient rights to perform the operation",
                        "schema": {}
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Auth API",
	Description:      "API for auth-service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
